Repository gorilla/handlers, pull requests merged in 2018-04, with the labels that each got.

#118 distinguish between explicit and implicit `*`
  cors.go
  cors_test.go
Labels: enhancement

#114 Add Vary header when allowedOrigins is *
  cors.go
Labels: documentation

#122 Revert "Add Vary header when allowedOrigins is * (#114)"
  cors.go
Labels: bug, build
