Repository gorilla/handlers, pull requests merged in 2019-07, with the labels that each got.

#163 Create release-drafter.yml
  .github/release-drafter.yml
Labels: build system

#164 Cleanup properly after hijacking a request
  logging.go
  logging_test.go
Labels: bug

#165 ProxyHeaders: mention X-Forwarded-Host in the docs
  proxy_headers.go
Labels: documentation

#157 Drop accept-encoding header when supported
  compress.go
  compress_test.go
Labels: enhancement

#166 docs: fix missing CircleCI badge
  README.md
Labels: build system, documentation
